labels: [lang-all]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in helping translate FastAPI docs! 🌍

        Please follow these instructions carefully to propose a new language translation. 🙏

        This structured process helps ensure translations can be properly maintained long-term.
  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      description: Please confirm and check all the following options.
      options:
        - label: I checked that this language is not already being translated in FastAPI docs.
          required: true
        - label: I searched existing discussions to ensure no one else proposed this language.
          required: true
        - label: I am a native speaker of the language I want to translate to.
          required: true
        - label: I understand I need to wait for maintainer approval before starting.
          required: true
  - type: input
    id: language
    attributes:
      label: Target Language
      description: What language do you want to translate FastAPI docs into?
      placeholder: e.g. Latin
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        Please explain:
        1. Why you want to add this language
        2. How you plan to maintain it long-term
      placeholder: |
        I want to add Latin translation because...
        My plan for maintaining it is...
    validations:
      required: true
  - type: textarea
    id: contributors
    attributes:
      label: Community Support
      description: |
        You need at least 2 other native speakers to help with translations.
        Ask them to comment on this discussion expressing their commitment.

        List their GitHub usernames below once they've commented.
      placeholder: |
        The following native speakers have committed to help:
        - @username1
        - @username2
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any other relevant information about your translation proposal
